development:
  adapter: sqlite3
  database: db/db_development.sqlite
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/db_test.sqlite
  timeout: 5000

production:
  adapter: postgresql
  database: db_production.sqlite
  timeout: 5000

cucumber:
  <<: *test